#!/bin/bash

[[ ! -f $HOME/.ssh/id_rsa ]] && echo 'note: id_rsa is not found, you may want to copy it manually later for auto-ssh-agent.'

echo '=> setting up sysroot...'

(mkpasswd > /etc/passwd && echo 'created /etc/passwd') || echo 'failed to setup /etc/passwd'
(mkgroup > /etc/group && echo 'created /etc/group') || echo 'failed to setup /etc/group'
mkdir -v -p /var/empty

echo '=> setting up out-side-of-tree cfg files...'

mkdir -p /etc/pacman.d/
cp -afv $HOME/.cache/__yadm_bootstrap_personal/pacman.d/mirrorlist.* /etc/pacman.d/

cat >> /etc/pacman.conf << EOF

# the followings are added by yadm

[git-for-windows]
Server = https://wingit.blob.core.windows.net/x86-64

[git-for-windows-mingw32]
Server = https://wingit.blob.core.windows.net/i686

# end of yadm modifications

EOF

curl -L https://ghproxy.com/https://raw.githubusercontent.com/git-for-windows/build-extra/HEAD/git-for-windows-keyring/git-for-windows.gpg | pacman-key --add -
pacman-key --lsign-key E8325679DFFF09668AD8D7B67115A57376871B1C
pacman-key --lsign-key 3B6D86A1BA7701CD0F23AED888138B9E1A9F3986

echo '=> installing oh-my-zsh...'

echo -n '!! please quit the shell, once it is installed. press any key to continue? '

read

bash -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

echo '=> installing zsh plugins and themes...'

git clone --depth=1 --no-tags --single-branch https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
git clone --depth=1 --no-tags --single-branch https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone --depth=1 --no-tags --single-branch https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

echo '=> overriding zsh config...'

cp -afv $HOME/.cache/__yadm_bootstrap_personal/.zshrc ~

echo '=> switching default shell to zsh...'

sed -iE "/^$USER:/ s|/bin/bash|/bin/zsh|g" /etc/passwd

echo '=> Done!'

echo 'note: restart the current shell (and other Cygwin proc) to apply the changes.'
