#!/bin/bash

#export EDITOR=nano

# example: homebrew
#export PATH="$(brew --prefix)/opt/curl/bin:$PATH"
#export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"
#export PATH="$(brew --prefix)/opt/gnu-tar/libexec/gnubin:$PATH"
#export PATH="$(brew --prefix)/opt/findutils/libexec/gnubin:$PATH"
#export PATH="$(brew --prefix)/opt/util-linux/bin:$PATH"
#export PATH="$(brew --prefix)/opt/util-linux/sbin:$PATH"
#export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"
