#!/usr/bin/zsh

__zshrc_plugin_prefix=/usr/share/zsh/plugins
__zshrc_theme=/usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

__zshrc_plugins=(
	zsh-history-substring-search
	zsh-syntax-highlighting
	zsh-autosuggestions
)

__cust_zsh_plugins=(
	sudo
)

# example: homebrew
#__zshrc_plugin_prefix=$(brew --prefix)/share
#__zshrc_theme=$(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
#FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

# example: macports
#__zshrc_plugin_prefix=/opt/local/share
