#!/bin/bash

__autossh_force=0
__autossh_kill=0

if [ -f ~/.cache/auto-ssh-agent.save ]; then
    echo "Sourcing ssh-agent profile..."
    . ~/.cache/auto-ssh-agent.save
fi

if [ "$#" -eq 1 ]; then
    if [ "$1" = "-f" -o "$1" = "--force" ]; then
        __autossh_force=1
    elif [ "$1" = "-k" -o "$1" = "--kill" ]; then
        __autossh_kill=1
    else
        echo "ensure-ssh-agent: Unknown arg: '$1'"
        return 1
    fi
elif [ "$#" -ne 0 ]; then
    echo "ensure-ssh-agent: Too many args"
    return 1
fi

__autossh_died=0

if ! kill -0 $SSH_AGENT_PID 2>/dev/null >/dev/null; then
    __autossh_died=1
else
    socat -u OPEN:/dev/null "UNIX-CONNECT:${SSH_AUTH_SOCK}" 2>/dev/null >/dev/null

    if [ "$?" -ne 0 ]; then
        __autossh_died=1
    fi
fi

if [ "$__autossh_died" -eq 1 ]; then
    echo "ssh-agent profile not found or invalid"
    if [ "$__autossh_kill" -eq 1 ]; then
        return 0
    fi
    if [ -f $HOME/.ssh/id_ed25519 -o "$__autossh_force" -eq 1 ]; then
        echo "starting a new ssh-agent..."
        rm -rf ~/.cache/auto-ssh-agent.save
        eval `ssh-agent -s`
        mkdir -p  ~/.cache
        echo '#!/bin/bash' > ~/.cache/auto-ssh-agent.save
        echo "export SSH_AGENT_PID=${SSH_AGENT_PID}" >> ~/.cache/auto-ssh-agent.save
        echo "export SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> ~/.cache/auto-ssh-agent.save
        echo "echo 'Injected ssh-agent profile.'" >> ~/.cache/auto-ssh-agent.save
        chmod +x ~/.cache/auto-ssh-agent.save
        source ~/.cache/auto-ssh-agent.save
        # ~/.bin/auto-ssh-agent/add-ssh-privkey  # Never save plain text passwd on any server
        ssh-add $HOME/.ssh/id_ed25519  # Manually add
    else
        echo "ensure-ssh-agent: No id_ed25519, Stop."
        return 1
    fi
elif [ "$__autossh_kill" -eq 1 ]; then
    kill $SSH_AGENT_PID
    echo "Killed ssh-agent"
    return 0
fi
